<?php

	//application details
		$apps[$x]['name'] = "SIP Profiles";
		$apps[$x]['uuid'] = "159a8da8-0e8c-a26b-6d5b-19c532b6d470";
		$apps[$x]['category'] = "";
		$apps[$x]['subcategory'] = "";
		$apps[$x]['version'] = "1.0";
		$apps[$x]['license'] = "Mozilla Public License 1.1";
		$apps[$x]['url'] = "http://www.fusionpbx.com";
//		$apps[$x]['description']['en-us'] = "Manage settings for the SIP profiles.";
		$apps[$x]['description']['en-us'] = "管理SIP配置文件的设置。";
		$apps[$x]['description']['zh-cn'] = "管理SIP配置文件的设置。";
		$apps[$x]['description']['ar-eg'] = "";
		$apps[$x]['description']['de-at'] = "Einstellungen der SIP-Profile verwalten.";
		$apps[$x]['description']['de-ch'] = "";
		$apps[$x]['description']['de-de'] = "Einstellungen der SIP-Profile verwalten.";
		$apps[$x]['description']['es-cl'] = "";
		$apps[$x]['description']['es-mx'] = "";
		$apps[$x]['description']['fr-ca'] = "";
		$apps[$x]['description']['fr-fr'] = "";
		$apps[$x]['description']['he-il'] = "";
		$apps[$x]['description']['it-it'] = "";
		$apps[$x]['description']['nl-nl'] = "";
		$apps[$x]['description']['pl-pl'] = "";
		$apps[$x]['description']['pt-br'] = "";
		$apps[$x]['description']['pt-pt'] = "";
		$apps[$x]['description']['ro-ro'] = "";
		$apps[$x]['description']['ru-ru'] = "";
		$apps[$x]['description']['sv-se'] = "";
		$apps[$x]['description']['uk-ua'] = "";

	//permission details
		$y=0;
		$apps[$x]['permissions'][$y]['name'] = "sip_profile_view";
		$apps[$x]['permissions'][$y]['menu']['uuid'] = "47014b1d-13ad-921c-313d-ca42c0424b37";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "sip_profile_add";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "sip_profile_edit";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "sip_profile_delete";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "sip_profile_setting_view";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "sip_profile_setting_add";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "sip_profile_setting_edit";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "sip_profile_setting_delete";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "sip_profile_setting_view";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "sip_profile_setting_add";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "sip_profile_setting_edit";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "sip_profile_setting_delete";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "sip_profile_domain_view";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "sip_profile_domain_add";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "sip_profile_domain_edit";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "sip_profile_domain_delete";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";

	//schema details
		$y=0;
		$apps[$x]['db'][$y]['table']['name'] = "v_sip_profiles";
		$apps[$x]['db'][$y]['table']['parent'] = "";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "sip_profile_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "sip_profile_name";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the SIP Profile name.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入SIP配置文件名。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入SIP配置文件名。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "sip_profile_hostname";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(255)";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "sip_profile_enabled";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "sip_profile_description";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the description.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入说明。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入说明。";

		$y++;
		$apps[$x]['db'][$y]['table']['name'] = "v_sip_profile_domains";
		$apps[$x]['db'][$y]['table']['parent'] = "v_sip_profiles";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "sip_profile_domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "sip_profile_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_sip_profile";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "sip_profile_uuid";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "sip_profile_domain_name";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the name.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入名称。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入名称。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "sip_profile_domain_alias";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enable or disable the alias.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "启用或禁用别名。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "启用或禁用别名。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "sip_profile_domain_parse";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enable or disable the parsing.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "启用或禁用分析。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "启用或禁用分析。";

		$y++;
		$apps[$x]['db'][$y]['table']['name'] = "v_sip_profile_settings";
		$apps[$x]['db'][$y]['table']['parent'] = "v_sip_profiles";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "sip_profile_setting_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "sip_profile_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "sip_profile_setting_name";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the name.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入名称。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入名称。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "sip_profile_setting_value";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the value.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入值。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入值。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "sip_profile_setting_enabled";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Choose to enable or disable this.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "选择启用或禁用此功能。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "选择启用或禁用此功能。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "sip_profile_setting_description";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the description.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入说明。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入说明。";

?>
