<?php

	//application details
		$apps[$x]['name'] = 'Email Templates';
		$apps[$x]['uuid'] = '8173e738-2523-46d5-8943-13883befd2fd';
		$apps[$x]['category'] = '';
		$apps[$x]['subcategory'] = '';
		$apps[$x]['version'] = '';
		$apps[$x]['license'] = 'Mozilla Public License 1.1';
		$apps[$x]['url'] = 'http://www.fusionpbx.com';
// 		$apps[$x]['description']['en-us'] = '';
		$apps[$x]['description']['en-us'] = '';
		$apps[$x]['description']['zh-cn'] = '';

	//permission details
		$y = 0;
		$apps[$x]['permissions'][$y]['name'] = 'email_template_view';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		//$apps[$x]['permissions'][$y]['groups'][] = 'admin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'email_template_add';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		//$apps[$x]['permissions'][$y]['groups'][] = 'admin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'email_template_edit';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		//$apps[$x]['permissions'][$y]['groups'][] = 'admin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'email_template_delete';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		//$apps[$x]['permissions'][$y]['groups'][] = 'admin';
		$y++;
		$apps[$x]['permissions'][$y]['name'] = 'email_template_all';
		$apps[$x]['permissions'][$y]['groups'][] = 'superadmin';
		//$apps[$x]['permissions'][$y]['groups'][] = 'admin';
		$y++;

	//Email Templates
		$y = 2;
		$apps[$x]['db'][$y]['table']['name'] = 'v_email_templates';
		$apps[$x]['db'][$y]['table']['parent'] = '';
		$z = 0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'email_template_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = 'primary';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'domain_uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = 'uuid';
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = 'text';
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = 'char(36)';
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = 'foreign';
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = 'v_domains';
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = 'domain_uuid';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'template_language';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
// 		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Enter the language.';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = '输入语言.';
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = '输入语言.';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'template_category';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
// 		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Select the category.';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = '选择类别.';
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = '选择类别.';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'template_subcategory';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
// 		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Enter the subcategory.';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = '选择子类别.';
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = '选择子类别.';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'template_subject';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
// 		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Enter the template subject.';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = '输入模板主题.';
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = '输入模板主题.';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'template_body';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
// 		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Enter the template body.';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = '输入模板正文.';
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = '输入模板正文.';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'template_type';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
// 		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Set the type as html or text.';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = '设置类别如html或text.';
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = '设置类别如html或text.';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'template_enabled';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
// 		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Set the status of the template.';
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = '设置模板状态.';
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = '设置模板状态.';
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = 'template_description';
		$apps[$x]['db'][$y]['fields'][$z]['type'] = 'text';
// 		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = 'Enter the description.';
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = '输入说明.';
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = '输入说明.';
		$z++;

?>
