<?php

	//application details
		$apps[$x]['name'] = "Contacts";
		$apps[$x]['uuid'] = "04481e0e-a478-c559-adad-52bd4174574c";
		$apps[$x]['category'] = "CRM";
		$apps[$x]['subcategory'] = "";
		$apps[$x]['version'] = "1.0";
		$apps[$x]['license'] = "Mozilla Public License 1.1";
		$apps[$x]['contact_url'] = "http://www.fusionpbx.com";
//		$apps[$x]['description']['en-us'] = "Provides a place to store contact information for individuals and organizations.";
		$apps[$x]['description']['en-us'] = "为个人和组织提供存储联系信息的位置。";
		$apps[$x]['description']['zh-cn'] = "为个人和组织提供存储联系信息的位置。";
		$apps[$x]['description']['ar-eg'] = "";
		$apps[$x]['description']['de-at'] = "Bietet einen Ort um Kontaktinformationen von Personen und Firmen zu speichern.";
		$apps[$x]['description']['de-ch'] = "";
		$apps[$x]['description']['de-de'] = "Bietet einen Ort um Kontaktinformationen von Personen und Firmen zu speichern.";
		$apps[$x]['description']['es-cl'] = "Provee un lugar para almacenar información de los contactos, para individuos u organizaciones";
		$apps[$x]['description']['es-mx'] = "";
		$apps[$x]['description']['fr-ca'] = "C'est un endroit pour posser information des contacts, personnes ou organizations.";
		$apps[$x]['description']['fr-fr'] = "Place pour stocker les information des contacts, personnes ou organizations.";
		$apps[$x]['description']['he-il'] = "";
		$apps[$x]['description']['it-it'] = "";
		$apps[$x]['description']['nl-nl'] = "";
		$apps[$x]['description']['pl-pl'] = "";
		$apps[$x]['description']['pt-br'] = "";
		$apps[$x]['description']['pt-pt'] = "Fornece um local para armazenar informações de contato para indivíduos e organizações.";
		$apps[$x]['description']['ro-ro'] = "";
		$apps[$x]['description']['ru-ru'] = "";
		$apps[$x]['description']['sv-se'] = "";
		$apps[$x]['description']['uk-ua'] = "";

	//permission details
		$y=0;
		$apps[$x]['permissions'][$y]['name'] = "contact_view";
		$apps[$x]['permissions'][$y]['menu']['uuid'] = "f14e6ab6-6565-d4e6-cbad-a51d2e3e8ec6";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_add";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_edit";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_delete";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_upload";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_address_view";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_address_add";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_address_edit";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_address_delete";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_phone_view";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_phone_add";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_phone_edit";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_phone_delete";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_note_view";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_note_add";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_note_edit";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_note_delete";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_group_view";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_group_add";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_group_edit";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_group_delete";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_user_view";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_user_add";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_user_edit";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_user_delete";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_email_view";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_email_add";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_email_edit";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_email_delete";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_url_view";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_url_add";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_url_edit";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_url_delete";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_setting_view";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_setting_add";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_setting_edit";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_setting_delete";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_relation_view";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_relation_add";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_relation_edit";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_relation_delete";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_extension_view";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$apps[$x]['permissions'][$y]['groups'][] = "admin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_time_view";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_time_add";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_time_edit";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "contact_time_delete";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;

	//schema details
		$y=0;
		$apps[$x]['db'][$y]['table']['name'] = "v_contacts";
		$apps[$x]['db'][$y]['table']['parent'] = "";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "id";
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = "contact_id";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "serial";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "integer";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "INT NOT NULL AUTO_INCREMENT";
		$apps[$x]['db'][$y]['fields'][$z]['deprecated'] = "true";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_domains";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "domain_uuid";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "v_id";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['deprecated'] = "true";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_parent_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_contacts";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "contact_uuid";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_type";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the type.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入类型。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入类型。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_organization";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the organization.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入组织。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入组织。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_name_prefix";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the name prefix.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入名称前缀。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入名称前缀。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_name_given";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the given name.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入给定的名称。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入给定的名称。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_name_middle";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the middle name.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入中间名。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入中间名。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_name_family";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the family name.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入族名称。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入族名称。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_name_suffix";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the name suffix.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入名称后缀。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入名称后缀。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_nickname";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the nickname.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入昵称。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入昵称。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_title";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the title.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入标题。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入标题。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_role";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the role.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入角色。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入角色。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_category";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the category.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入类别。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入类别。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_url";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the website address.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入网站地址。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入网站地址。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_time_zone";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the time zone.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入时区。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入时区。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_note";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the notes.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入注释。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入注释。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "last_mod_date";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "last_mod_user";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";

		$y++;
		$apps[$x]['db'][$y]['table']['name'] = "v_contact_addresses";
		$apps[$x]['db'][$y]['table']['parent'] = "v_contacts";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_address_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_domains";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "domain_uuid";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_contacts";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "contact_uuid";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "address_type";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Used for vCard format.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "用于vCard格式。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "用于vCard格式。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "address_label";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Custom label for an address.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "地址的自定义标签。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "地址的自定义标签。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "address_primary";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "numeric";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Designate a primary address.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "指定主地址。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "指定主地址。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "address_street";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the street address.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入街道地址。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入街道地址。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "address_extended";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the extended address.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入扩展地址。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入扩展地址。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "address_community";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the community.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "进入社区。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "进入社区。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "address_locality";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the city.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入城市。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入城市。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "address_region";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the state or province.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入省/市/自治区。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入省/市/自治区。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "address_postal_code";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the postal code.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入邮政编码。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入邮政编码。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "address_country";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the country.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入国家。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入国家。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "address_latitude";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the latitude.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入纬度。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入纬度。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "address_longitude";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the longitude.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入经度。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入经度。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "address_description";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the description.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入说明。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入说明。";

		$y++;
		$apps[$x]['db'][$y]['table']['name'] = "v_contact_phones";
		$apps[$x]['db'][$y]['table']['parent'] = "v_contacts";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_phone_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_domains";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "domain_uuid";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_contacts";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "contact_uuid";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "phone_type_voice";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "numeric";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Number is used for voice calls.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "号码用于语音通话。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "号码用于语音通话。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "phone_type_fax";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "numeric";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Number is used for fax calls.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "号码用于传真呼叫。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "号码用于传真呼叫。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "phone_type_video";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "numeric";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Number is used for video calls.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "号码用于视频通话。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "号码用于视频通话。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "phone_type_text";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "numeric";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Number is used for text messages.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "数字用于文本消息。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "数字用于文本消息。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "phone_label";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Custom label for the number";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "数字的自定义标签";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "数字的自定义标签";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "phone_primary";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "numeric";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Designate a primary number.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "指定一个主号码。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "指定一个主号码。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "phone_number";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the number.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入数字。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入数字。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "phone_extension";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the extension.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入扩展名。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入扩展名。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "phone_speed_dial";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the speed dial.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入快速拨号。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入快速拨号。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "phone_description";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the description.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入说明。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入说明。";

		$y++;
		$apps[$x]['db'][$y]['table']['name'] = "v_contact_notes";
		$apps[$x]['db'][$y]['table']['parent'] = "v_contacts";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "id";
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = "contacts_note_id";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "serial";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "integer";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "INT NOT NULL AUTO_INCREMENT";
		$apps[$x]['db'][$y]['fields'][$z]['deprecated'] = "true";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_note_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_domains";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "domain_uuid";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "v_id";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['deprecated'] = "true";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_id";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "numeric";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Contact ID";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "联系人ID";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "联系人ID";
		$apps[$x]['db'][$y]['fields'][$z]['deprecated'] = "true";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_contacts";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "contact_uuid";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "contact_note";
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = "notes";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "last_mod_date";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "last_mod_user";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";

		$y++;
		$apps[$x]['db'][$y]['table']['name'] = "v_contact_users";
		$apps[$x]['db'][$y]['table']['parent'] = "v_contacts";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_user_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_domains";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "domain_uuid";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_contacts";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "contact_uuid";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "user_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_users";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "user_uuid";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";

		$y++;
		$apps[$x]['db'][$y]['table']['name'] = "v_contact_groups";
		$apps[$x]['db'][$y]['table']['parent'] = "v_contacts";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name']['text'] = "contact_group_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['name']['deprecated'] = "contact_groups_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_domains";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "domain_uuid";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_contacts";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "contact_uuid";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "group_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_groups";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "group_uuid";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";

		$y++;
		$apps[$x]['db'][$y]['table']['name'] = "v_contact_settings";
		$apps[$x]['db'][$y]['table']['parent'] = "v_contacts";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_setting_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_contacts";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "contact_uuid";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_setting_category";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the category.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入类别。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入类别。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_setting_subcategory";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the subcategory.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入子类别。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入子类别。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_setting_name";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the name.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入名称。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入名称。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_setting_value";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the value.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入值。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入值。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_setting_order";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "numeric";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_setting_enabled";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_setting_description";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";

		$y++;
		$apps[$x]['db'][$y]['table']['name'] = "v_contact_relations";
		$apps[$x]['db'][$y]['table']['parent'] = "v_contacts";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_relation_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_contacts";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "contact_uuid";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "relation_label";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "relation_contact_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_contacts";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "contact_uuid";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";

		$y++;
		$apps[$x]['db'][$y]['table']['name'] = "v_contact_emails";
		$apps[$x]['db'][$y]['table']['parent'] = "v_contacts";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_email_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_domains";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "domain_uuid";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_contacts";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "contact_uuid";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "email_label";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Custom label for the email address.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "电子邮件地址的自定义标签。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "电子邮件地址的自定义标签。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "email_primary";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "numeric";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Designate a primary address.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "指定主地址。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "指定主地址。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "email_address";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the email address.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入电子邮件地址。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入电子邮件地址。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "email_description";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the email description.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入电子邮件说明。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入电子邮件说明。";

		$y++;
		$apps[$x]['db'][$y]['table']['name'] = "v_contact_urls";
		$apps[$x]['db'][$y]['table']['parent'] = "v_contacts";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_url_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_domains";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "domain_uuid";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_contacts";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "contact_uuid";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "url_type";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Defines the purpose or protocol for the URL.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "定义URL的目的或协议。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "定义URL的目的或协议。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "url_label";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Custom label for the url.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "URL的自定义标签。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "URL的自定义标签。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "url_primary";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "numeric";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Designate a primary address.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "指定主地址。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "指定主地址。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "url_address";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "The actual URL address.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "实际的URL地址。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "实际的URL地址。";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "url_description";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Enter the URL description.";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "输入URL说明。";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "输入URL说明。";

		$y++;
		$apps[$x]['db'][$y]['table']['name'] = "v_contact_times";
		$apps[$x]['db'][$y]['table']['parent'] = "v_contacts";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "domain_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_domains";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "domain_uuid";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_time_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "contact_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_contact";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "contact_uuid";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "user_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "foreign";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['table'] = "v_users";
		$apps[$x]['db'][$y]['fields'][$z]['key']['reference']['field'] = "user_uuid";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "time_start";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "timestamp";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Start";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "起点";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "起点";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "time_stop";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "timestamp";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Stop";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "停止";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "停止";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "time_description";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
//		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "Description";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "说明";
		$apps[$x]['db'][$y]['fields'][$z]['description']['zh-cn'] = "说明";

?>
